# Generated by Django 2.2.24 on 2023-04-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_booleanfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='BooleanField',
            new_name='new_building',
        ),
    ]
