# Generated by Django 2.2.24 on 2023-04-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230424_1435'),
    ]

    operations = [
    ]



