# Generated by Django 2.2.24 on 2023-04-24 12:07

from django.db import migrations


def update_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = int(flat.construction_year) >= 2015
        print(flat.new_building, flat.construction_year)
        break


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230424_1443'),
    ]

    operations = [
        migrations.RunPython(update_new_building)
    ]
