# Generated by Django 2.2.24 on 2023-04-24 12:35

from django.db import migrations


def update_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = int(flat.construction_year) >= 2015
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230424_1507'),
    ]

    operations = [
        migrations.RunPython(update_new_building)
    ]

