# Generated by Django 2.2.24 on 2023-04-24 12:35

from django.db import migrations


def update_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230424_1507'),
    ]

    operations = [
        migrations.RunPython(update_new_building)
    ]

