# Generated by Django 2.2.24 on 2023-04-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230424_1535'),
    ]

    operations = [
    ]
