# Generated by Django 2.2.24 on 2023-04-25 04:56
import phonenumbers

from django.db import migrations


def update_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.owner_pure_phone = f'+7{owner_pure_phone.national_number}'
        print(f'start {flat.owners_phonenumber} end number {flat.owner_pure_phone}')
        flat.save()
        # w = 2/0



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(update_phone_numbers)
    ]
