# Generated by Django 2.2.24 on 2023-04-25 06:35
import phonenumbers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230425_0932'),
    ]

    operations = [
    ]
