# Generated by Django 2.2.24 on 2023-04-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20230426_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
