# Generated by Django 2.2.24 on 2023-04-26 06:03

from django.db import migrations
import phonenumbers


def update_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(name='Баранов Кирилл Денисович')
        if created:
            owner.flats.set([flat])
            owner.save()
            print(f' owner {owner.name} {created}')
            print(f'count {owner.flats.count()}')
        break



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20230426_0842'),
    ]

    operations = [
        migrations.RunPython(update_phone_numbers)
    ]
